# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

stages:
  - install
  - lint

install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules

eslint:
  stage: lint
  script:
    - npm run eslint
  dependencies:
    - install

stylelint:
  stage: lint
  script:
    - npm run stylelint
  dependencies:
    - install

htmlhint:
  stage: lint
  script:
    - npm run htmlhint
  dependencies:
    - install
